experiment: yolox-eval-webimages
indir: DRV/TOMS/test_sets/Dartmouth_Synthetic_fskip10/
outdir: MOD/results/yolox-eval-webimages/{run-id}
ckpt: MOD/results/yolox-train-webimages/yolox-train-webimages_1637919956_962ee055/yolox-train-webimages/best_ckpt.pth
model_name: yolox-s
conf: 0.001
nmsthre: 0.3
val_subdir: images
val_ann: test.json
subscription: 15c1afea-319d-4e83-874a-8c989125f3b9
resource_group: rg-surgicaldataplatform-stage
docker_image: yolox:0.3
experiment: yolox-train-webimages
workspace: ml-toms-patient2
environment: yolox
datastore: sdpdatadev
container_registry:
  address: kzsdp.azurecr.io
  username: kzsdp
  password: S0=sd8AF+mKS4xsCj2FTksywbMp0DDus
