experiment: yolox-eval-webimages
indir: ../test_sets/Dartmouth_Synthetic_fskip10/
outdir: ../results/yolox-eval-webimages/eval_results
ckpt: ../results/yolox-train-webimages/model_outputs/best_ckpt.pth
model_name: yolox-s
conf: 0.001
nmsthre: 0.3
val_subdir: images
val_ann: test.json
