name: dartmouth_Batch01
indir: ../data/Batch_01/frames_CH010
outdir: ../results/yolox-train-cgiweb/test_results/bbox_infered
ckpt: ../results/yolox-train-cgiweb/model_outputs/best_ckpt.pth
model_name: yolox-s
conf: 0.2
nms: 0.4
