subscription: 
resource_group: 
docker_image: yolox:0.3
experiment: yolox-train
workspace: 
environment: yolox
datastore: 
indir: train_sets/Web_Images/hospital_beds
outdir: results/yolox-train-webimages
max_epoch: 300
batch_size: 15
model_name: yolox-s
augment: False
num_classes: 1
container_registry:
  address: 
  username: 
  password: 
