experiment: yolox-train-webimages
environment: yolox
indir: ../Data/train_sets/Web_Images/hospital_beds
outdir: ../Data/results/yolox-train-webimages
max_epoch: 10
batch_size: 5
model_name: yolox-s
augment: False
num_classes: 1
