subscription: 
resource_group: 
docker_image: yolox:0.3
experiment: yolox-train-cgi
workspace: 
environment: yolox
datastore: 
indir: train_sets/WebImages
outdir: results/yolox-train-cgiweb
max_epoch: 600
batch_size: 15
model_name: yolox-s
augment: True
num_classes: 1
container_registry:
  address: 
  username: 
  password: 
