subscription: 15c1afea-319d-4e83-874a-8c989125f3b9
resource_group: rg-surgicaldataplatform-stage
docker_image: yolox:0.3
experiment: yolox-train-door-detect-eke
workspace: AzureTesting
environment: yolox
datastore: testds
indir: DRV/TOMS/train_sets/door_dataset_310122/trainset/
outdir: MOD/results/yolox-train-door-detect-eke/{run-id}
max_epoch: 3
batch_size: 32
model_name: yolox-m
augment: True
mosaic_enabled: True
fp16: True
num_classes: 1
container_registry:
  address: kzsdp.azurecr.io
  username: kzsdp
  password: S0=sd8AF+mKS4xsCj2FTksywbMp0DDus
