subscription: 15c1afea-319d-4e83-874a-8c989125f3b9
resource_group: rg-surgicaldataplatform-stage
docker_image: yolox:0.3
experiment: yolox-train-cgiblender
workspace: ml-toms-patient2
environment: yolox
datastore: sdpdatadev
input_path: DRV/TOMS/train_sets/CGI_Blender/Batch01
max_epoch: 300
batch_size: 15
model_name: yolox-s
augment: False
num_classes: 1
container_registry:
  address: kzsdp.azurecr.io
  username: kzsdp
  password: 14RjwP=Rq4mFyvmi8V6zM239anQJKPzG
